### ISSUE TITLE
Usage customization question

### ISSUE THREAD

**Issue by ahogen** [jongracecox/pylint-exit#1]
Thanks for this useful module! Just starting using it and it's helped a lot!

The readme says:

> This list is stored in EXIT_CODES_LIST, which can be customised if needed.

How can I customize this if I'm using `pylint-exit` on the command line, not as a python script?

I want to have `pylint-exit` return with a non-zero exit code if `pylint` issues error messages.

Thanks!

**Comment by abloch** [comment]
👍

**Comment by ahogen** [comment]
I really needed this, so I had to ditch `pylint-exit`. It was faster for me to simply write my own Bash script to do this.

For anyone interested (@abloch), I've shared my Bash script publicly. https://gist.github.com/ahogen/7e6150626c75d9000e009963ce9ce9a9

**Comment by abloch** [comment]
I also ended up doing this myself, but I chose a one-liner.
as the only exit codes I support are 0 and 4 (warnings) - the below worked for me
`|| python -c "import sys;sys.exit($? not in [0,4])"`
